final List<String> philippineCities = [
  'Alaminos', 'Angeles', 'Antipolo', 'Bacolod', 'Bacoor', 'Bago',
  'Baguio', 'Bais', 'Balanga', 'Batac', 'Batangas', 'Bayawan',
  'Baybay', 'Bayugan', 'Biñan', 'Bislig', 'Bogo', 'Borongan',
  'Butuan', 'Cabadbaran', 'Cabanatuan', 'Cabuyao', 'Cadiz',
  'Cagayan de Oro', 'Calamba', 'Calapan', 'Calbayog', 'Caloocan',
  'Candon', 'Canlaon', 'Carcar', 'Catbalogan', 'Cauayan',
  'Cavite', 'Cebu', 'Cotabato', 'Dagupan', 'Danao', 'Dapitan',
  'Dasmariñas', 'Davao', 'Digos', 'Dipolog', 'Dumaguete',
  'El Salvador', 'Escalante', 'Gapan', 'General Santos',
  'General Trias', 'Gingoog', 'Guihulngan', 'Himamaylan',
  'Iligan', 'Iloilo', 'Imus', 'Iriga', 'Isabela', 'Kabankalan',
  'Kidapawan', 'Koronadal', 'La Carlota', 'Lamitan', 'Laoag',
  'Lapu-Lapu', 'Las Piñas', 'Legazpi', 'Ligao', 'Lipa',
  'Lucena', 'Maasin', 'Mabalacat', 'Makati', 'Malabon',
  'Malaybalay', 'Malolos', 'Mandaluyong', 'Mandaue', 'Manila',
  'Marawi', 'Marikina', 'Masbate', 'Mati', 'Meycauayan',
  'Muñoz', 'Muntinlupa', 'Naga', 'Nasugbu', 'Navax', 'Olongapo',
  'Ormoc', 'Oroquieta', 'Ozamiz', 'Pagadian', 'Panabo','Pampanga',
  'Parañaque', 'Pasay', 'Pasig', 'Passi', 'Pateros',
  'Puerto Princesa', 'Quezon', 'Roxas', 'Sagay', 'Samal',
  'San Carlos', 'San Fernando', 'San Jose', 'San Jose del Monte',
  'San Juan', 'San Pablo', 'San Pedro', 'Santa Rosa', 'Santiago',
  'Silay', 'Sipalay', 'Sorsogon', 'Surigao', 'Tabaco',
  'Tabuk', 'Tacloban', 'Tacurong', 'Tagaytay', 'Tagbilaran',
  'Taguig', 'Tagum', 'Talisay', 'Tanauan', 'Tandag',
  'Tangub', 'Tarlac', 'Tayabas', 'Toledo', 'Trece Martires',
  'Tuguegarao', 'Urdaneta', 'Valencia', 'Valenzuela', 'Vigan',
  'Zamboanga'
];
